#!/bin/sh

# gse-lib - Library for gnome-shell extensions
# Copyright (C) 2019 Philippe Troin <phil@fifi.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eu

progname="${0##*/}"
project_base="$(cd "$(dirname "$0")"/.. && pwd)"
gse_lib_base="$project_base"/gse-lib

if [ -d "$project_base/po" ]
then
  cp -a "$gse_lib_base"/po/meson.build "$project_base/po/"
fi

m4 -P -I "$project_base" "$gse_lib_base/meson.build.m4" > "$project_base/meson.build"
