#!/bin/sh

# Soft-brightness - Control the display's brightness via an alpha channel.
# Copyright (C) 2019 Philippe Troin <phil@fifi.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eu

progname="${0##*/}"

if [ $# != 3 ]
then
  echo 1>&2 "usage: $progname <install_dir> <output_dir> <output_file>"
  exit 1
fi

install_dir="$1"
output_dir="$(cd "$2" && pwd)"
output_file="$3"

tmpdir=""
clean() {
  local xit=$? xit2=0
  rm -fr "$tmpdir" || xit2=$?
  if [ "$xit" -eq 0 ]
  then
    xit=$xit2
  fi
  trap - EXIT
  exit $xit
}

trap clean INT TERM HUP QUIT EXIT

tmpdir="$(mktemp -d "$(pwd)/make-extension-XXXXXXX.tmp")"
DESTDIR="$tmpdir" ninja install
cd "$tmpdir$install_dir" && zip -r "$output_dir/$output_file" *
